# Sensitivity to the LLOQ of the study assay

Generated by `scripts/48_lloq_summary.R` from `results/lloq/` (pre-registered in `config/prereg_20260926.yaml`, section2; the study LLOQ is set in `config/assay.yaml`, currently 0.078 mg/L). The same subjects, sampling times and residual draws are re-censored at each LLOQ (paired). Primary residual variant: as estimated (additive SD 0.03 mg/L); secondary: additive SD scaled by LLOQ/0.078.

## Individual level (B0, 60 to 90 kg, 20,000 subjects per model)

- 2016 model: reliability under criteria (i) 84.2% (LLOQ 0.02) to 88.0% (LLOQ 0.5) (residual as estimated) [84.6% (LLOQ 0.02) to 87.8% (LLOQ 0.5) with the scaled residual]; criteria (ii) 80.9% (LLOQ 0.02) to 79.8% (LLOQ 0.5); lambda-z not estimable 0.72% (LLOQ 0.02) to 1.88% (LLOQ 0.5); true coverage below 80% in 0.00% (LLOQ 0.02) to 0.00% (LLOQ 0.5) of subjects; median true extrapolated share 0.03% (LLOQ 0.02) to 1.00% (LLOQ 0.5); median tlast 41.6 days (LLOQ 0.02) to 34.5 days (LLOQ 0.5).
- Model 1: reliability under criteria (i) 85.9% (LLOQ 0.02) to 95.0% (LLOQ 0.5) (residual as estimated) [89.4% (LLOQ 0.02) to 94.9% (LLOQ 0.5) with the scaled residual]; criteria (ii) 81.4% (LLOQ 0.02) to 83.6% (LLOQ 0.5); lambda-z not estimable 0.28% (LLOQ 0.02) to 0.83% (LLOQ 0.5); true coverage below 80% in 0.00% (LLOQ 0.02) to 0.00% (LLOQ 0.5) of subjects; median true extrapolated share 0.05% (LLOQ 0.02) to 0.96% (LLOQ 0.5); median tlast 42.2 days (LLOQ 0.02) to 35.1 days (LLOQ 0.5).

## Cliff capture (current schedule)

- 2016 model: the true concentration reaches the LLOQ at a median of study Day 38.6 (LLOQ 0.02 mg/L), 38.5 (0.078) and 37.7 (0.5); median cliff length 1.52, 1.38 and 0.63 days; subjects with 1 or more samples in the cliff (1-day definition, nominal days): 22.2%, 20.0% and 8.8%; 2 or more: 0.0%, 0.0%, 0.0%.
- Model 1: the true concentration reaches the LLOQ at a median of study Day 40.9 (LLOQ 0.02 mg/L), 40.8 (0.078) and 40.0 (0.5); median cliff length 1.53, 1.38 and 0.64 days; subjects with 1 or more samples in the cliff (1-day definition, nominal days): 20.9%, 18.8% and 8.6%; 2 or more: 0.0%, 0.0%, 0.0%.

## Boundary type I error, 2016 model (5,000 trials; Vmax both directions and F down; residual as estimated)

- P2: M0 2.22% to 4.22% (maximum F down, LLOQ 0.02, 4.22 [3.70, 4.81]); M1 2.60% to 4.62% (maximum F down, LLOQ 0.02, 4.62 [4.07, 5.24]); cells (of 3 cells x 6 LLOQs) with Wilson lower bound above 5%: M0 0, M1 0.
- G2-A(ii): M0 6.74% to 28.70% (maximum Vmax down, LLOQ 0.5, 28.70 [27.46, 29.97]); M1 6.84% to 28.52% (maximum Vmax down, LLOQ 0.5, 28.52 [27.29, 29.79]); cells (of 3 cells x 6 LLOQs) with Wilson lower bound above 5%: M0 18, M1 18.
- G2-B: M0 3.58% to 17.54% (maximum Vmax up, LLOQ 0.5, 17.54 [16.51, 18.62]); M1 3.92% to 18.36% (maximum Vmax up, LLOQ 0.5, 18.36 [17.31, 19.46]); cells (of 3 cells x 6 LLOQs) with Wilson lower bound above 5%: M0 16, M1 17.
- Largest paired change of P2 versus LLOQ 0.078: M1, Vmax up, LLOQ 0.02: +0.72 points [+0.49, +0.95].
- Power of P2 for identical products: M0 99.48% to 99.60%, M1 99.60% to 99.66% across the LLOQs.

Verification: at LLOQ 0.078 with the residual as estimated, the individual-level results equal the stored results (subject level and summary), the cliff results equal the stored cliff files, and the trial-level M0 equals the stored operating-characteristic trials; the scaled residual at 0.078 equals the unscaled one.
